baseURL = "/"
languageCode = "fr-fr"
DefaultContentLanguage = "fr"

title = "Les Jeux de Rôles BCA"
theme = "docdock"
themesdir = "themes"
showVisitedLinks = true

[params]
editURL = "https://github.com/SpaceFox/bca-jdr/edit/master/content/"
noHomeIcon = false # default is false
noSearch = false # default is false
showVisitedLinks = true # default is false
# themeStyle = "theme" # overide base css
themeVariant = "blue" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"

[outputFormats.Pandoc]
name = "Pandoc"
mediaType = "text/plain"
#path = "pandoc"
isPlainText = true
isHTML = false
notAlternative = true

[outputs]
  home = [ "HTML", "RSS", "JSON"]
  page = ["HTML", "Pandoc"]

[[menu.shortcuts]]
pre = "<h3>Et aussi…</h3>"
name = "<i class='fa fa-github'></i> Proposer une modification"
identifier = "ds"
url = "https://github.com/SpaceFox/bca-jdr/issues"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-legal'></i> Informations légales"
url = "/licence"
weight = 20
